In [15]:
import pandas as pd
from azureml.core.authentication import InteractiveLoginAuthentication
interactive_auth = InteractiveLoginAuthentication(tenant_id="f2ec3ef9-cca6-46ec-be61-845d74fcae94")

In [16]:
from azureml.core import Workspace, Dataset
subscription_id = 'ade92c9f-9e5b-4355-812d-4d6826ffb5d0'
resource_group = 'AI-RD'
workspace_name = 'AlanML'
workspace = Workspace(subscription_id, resource_group, workspace_name)
dataset = Dataset.get_by_name(workspace, name='workplace-data')
df = dataset.to_pandas_dataframe().drop(columns = ["Column3"])

In [17]:
cases =df["RecentWorkplaces"]
datesDF = df["CreatedOnDate"]
arrayOfPlaces = []
dates = []
df["FuzzyMatch"] =""
#df.loc[[3],"FuzzyMatch"] ="test"

In [18]:
from fuzzywuzzy import fuzz
import datetime

In [19]:
for case in cases:
    arrayOfPlaces.append(case)

In [23]:
def createMatches():
    arrayOfPlacesThatMatch = []
    Quantity = {}
    straightLength = len(arrayOfPlaces)-1
    
    for index,place in enumerate(range(straightLength)):

        Str1 = arrayOfPlaces[place]

        if Str1 not in Quantity:
            Quantity[Str1] = "" 

        for placeToMatch in range (straightLength):
            Str2 = arrayOfPlaces[placeToMatch]       
            ratio = fuzz.ratio(Str1,Str2)

            if ratio > 60:
                if Str2 not in Quantity:
                    arrayOfPlacesThatMatch.append(Str2)
                    
                    Quantity[Str1] = arrayOfPlacesThatMatch
        if arrayOfPlacesThatMatch:
            df.loc[[index],"FuzzyMatch"] = str(arrayOfPlacesThatMatch)
        arrayOfPlacesThatMatch = []
    return Quantity
Quantity=createMatches()
#df

,CreatedOnDate,RecentWorkplaces,FuzzyMatch
0,2020-08-13,None,
1,2020-08-11,Not working since start of lockdown,['Lisburn Bowl- Hasnt worked there since start...
2,2020-08-13,None,
3,2020-08-13,None,
4,2020-08-13,None,
5,2020-06-03,None,
6,2020-06-03,None,
7,2020-06-03,"Amelio Utilities Ltd, Finaghy",
8,2020-06-03,works The Stables Lady Dickson Pk Belfast prev...,
9,2020-06-03,working from home - 10 weeks,"['Working from home - notified employer', 'NIE..."
10,2020-06-03,None,
11,2020-06-03,"Hollywood Arches, Health Centre, Belfast",
12,2020-06-03,None,
13,2020-06-03,na,['n/a']
14,2020-06-03,None,
15,2020-06-03,"Based in Belfast, has been off work 4/5 weeks",['Clareview Nursing Home (has been off work fo...
16,2020-06-03,None,
17,2020-06-03,"Curran Oral Surgery, Lisburn Road",
18,2020-06-03,Working from home - notified employer,"['Working from home', 'Working from home', 'Wo..."
19,2020-06-03,Blair House care Home Newtownards. Agency is S...,
20,2020-06-02,"Bradley Manor Care Home, Belfast","['Our Ladys Nursing Home, Belfast', 'Carrick M..."
21,2020-06-02,None,
22,2020-06-02,None,
23,2020-06-01,Gardening - still does a bit,
24,2020-06-01,"St Marys and Christian Brothers Grammar, Belfast",
25,2020-06-01,Community - Health care Worker,['Community Annes Homecare']
26,2020-06-01,None,
27,2020-06-01,Anns Home Care In Community Setting - Market H...,
28,2020-06-01,None,
29,2020-06-01,Glanbia Cheese Factory,
...,...,...,...
10283,2020-10-05,None,
10284,2020-10-05,None,
10285,2020-10-05,None,
10286,2020-10-05,None,
10287,2020-10-05,None,
10288,2020-10-05,None,
10289,2020-10-05,None,
10290,2020-10-05,None,
10291,2020-10-05,None,
10292,2020-10-05,None,
10293,2020-10-05,None,
10294,2020-10-05,None,
10295,2020-10-05,None,
10296,2020-10-05,None,
10297,2020-10-05,None,
10298,2020-10-05,None,
10299,2020-10-05,None,
10300,2020-10-05,None,
10301,2020-10-05,None,
10302,2020-10-05,None,
10303,2020-10-05,None,
10304,2020-10-05,None,
10305,2020-10-05,None,
10306,2020-10-05,None,
10307,2020-10-05,None,
10308,2020-10-05,None,
10309,2020-10-05,None,
10310,2020-10-05,None,
10311,2020-10-05,None,
10312,2020-10-05,None,

In [26]:
dfGroupedwithFuzzyMatchColumn = df.groupby(["CreatedOnDate"])[["RecentWorkplaces","FuzzyMatch"]].sum().reset_index("CreatedOnDate")
dfGroupedwithRecentWorkplacesColumn = df.groupby(["CreatedOnDate"])[["RecentWorkplaces"]].sum().reset_index("CreatedOnDate")
both = pd.concat([dfGroupedwithFuzzyMatchColumn,dfGroupedwithRecentWorkplacesColumn], axis=0, ignore_index=True, sort=False)
#both
#dfGroupedwithRecentWorkplacesColumn
#dfGroupedwithFuzzyMatchColumn
# for i in df["RecentWorkplaces"]:
#     print(i)

    CreatedOnDate RecentWorkplaces
0      2020-05-25              NaN
1      2020-05-26              NaN
2      2020-05-27              NaN
3      2020-05-28              NaN
4      2020-05-29              NaN
5      2020-05-30              NaN
6      2020-05-31              NaN
7      2020-06-01              NaN
8      2020-06-02              NaN
9      2020-06-03              NaN
10     2020-06-04              NaN
11     2020-06-05              NaN
12     2020-06-06              NaN
13     2020-06-07              NaN
14     2020-06-08              NaN
15     2020-06-09              NaN
16     2020-06-10              NaN
17     2020-06-11              NaN
18     2020-06-12              NaN
19     2020-06-13              NaN
20     2020-06-14              NaN
21     2020-06-15              NaN
22     2020-06-16              NaN
23     2020-06-17              NaN
24     2020-06-18              NaN
25     2020-06-19              NaN
26     2020-06-21              NaN
27     2020-06-22              NaN
28     2020-06-23                0
29     2020-06-24              NaN
..            ...              ...
102    2020-09-06              NaN
103    2020-09-07              NaN
104    2020-09-08              NaN
105    2020-09-09              NaN
106    2020-09-10              NaN
107    2020-09-11              NaN
108    2020-09-12              NaN
109    2020-09-13              NaN
110    2020-09-14              NaN
111    2020-09-15              NaN
112    2020-09-16              NaN
113    2020-09-17              NaN
114    2020-09-18              NaN
115    2020-09-19              NaN
116    2020-09-20              NaN
117    2020-09-21              NaN
118    2020-09-22              NaN
119    2020-09-23              NaN
120    2020-09-24              NaN
121    2020-09-25              NaN
122    2020-09-26              NaN
123    2020-09-27              NaN
124    2020-09-28              NaN
125    2020-09-29              NaN
126    2020-09-30              NaN
127    2020-10-01              NaN
128    2020-10-02              NaN
129    2020-10-03              NaN
130    2020-10-04              NaN
131    2020-10-05              NaN

[132 rows x 2 columns]

In [22]:
# for i,k in dfGroupedwithRecentWorkplacesColumn.T.iteritems():
#     print(k)
# df.groupby('CreatedOnDate').agg(["FuzzyMatch"])
# for k,v in Quantity.items():
#     print("Original:", k, "--- Matches: ", v)

In [ ]:
# for columnName,rowMatch in df.T.iteritems():
#     for i in rowMatch:
#         print(i)